spring.application.name=studyrats

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/studyrats
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=studyrats-super-secret-key-for-jwt-token-2026
jwt.expiration=900000

security.pepper=GLOBAL_PEPPER_SECRET